name: Android

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'tools platform-tools platforms;android-30 build-tools;35.0.0'

      - name: Install dependencies
        run: |
          rustup target add aarch64-linux-android
          cargo install cargo-apk

      - name: Build
        run: |
          cargo apk build --target aarch64-linux-android --lib

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: target/debug/apk
